// Codes d'erreur FranceConnect
export const FC_ERROR_CODES = {
  FRANCECONNECT_ERROR: "FRANCECONNECT_ERROR",
  FC_CANCELLED: "FC_CANCELLED",
  FC_SERVER_ERROR: "FC_SERVER_ERROR",
  FC_INVALID_STATE: "FC_INVALID_STATE",
  FC_TOKEN_ERROR: "FC_TOKEN_ERROR",
  FC_AUTH_FAILED: "FC_AUTH_FAILED",
  FC_MISSING_PARAMS: "FC_MISSING_PARAMS",
  FC_INVALID_REQUEST: "FC_INVALID_REQUEST",
  FC_UNAUTHORIZED: "FC_UNAUTHORIZED",
} as const;
