services:
  fonds-prevention-argile-development:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    command: pnpm start:dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Utile pour le hot-reload sous Windows/WSL
  postgres:
    image: postgres:16-alpine
    container_name: fonds-argile-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-fonds_argile}
      POSTGRES_USER: ${DB_USER:-fonds_argile_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fonds_argile_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-fonds_argile_user} -d ${DB_NAME:-fonds_argile}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local