services:
  fonds-prevention-argile-development:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    command: sh -c "pnpm install --frozen-lockfile && pnpm start:dev"
    volumes:
      - .:/app
      - node_modules:/app/node_modules 
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - CI=true
    depends_on:
      - postgres
      - mailhog

  postgres:
    image: postgres:16-alpine
    container_name: fonds-argile-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-fonds_argile}
      POSTGRES_USER: ${DB_USER:-fonds_argile_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fonds_argile_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-fonds_argile_user} -d ${DB_NAME:-fonds_argile}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: fonds-argile-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    driver: local
  node_modules:
    driver: local