packages:
  - "."

savePrefix: "~"
minimumReleaseAge: 10080 # one week in minutes
trustPolicy: no-downgrade

onlyBuiltDependencies:
  - "@next/swc-linux-x64-gnu"
  - "@next/swc-darwin-arm64"
  - "@next/swc-darwin-x64"
  - "@next/swc-win32-x64-msvc"
  - esbuild
  - sharp
