/**
 * Codes d'erreur d'accès
 */
export enum AccessErrorCode {
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE",
  WRONG_AUTH_METHOD = "WRONG_AUTH_METHOD",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  AGENT_NOT_FOUND = "AGENT_NOT_FOUND",
}
