export { default as contentLayout } from "./layout.json";
export { default as contentComponents } from "./components.json";
export { default as contentHomePage } from "./homePage.json";
export { default as contentAccessibilityPage } from "./accessibilityPage.json";
export { default as contentStatisticsPage } from "./statisticsPage.json";
export { default as contentLegalNoticePage } from "./legalNoticePage.json";
export { default as contentNotFoundPage } from "./notFoundPage.json";
export { default as contentSimulationPage } from "./simulationPage.json";
export { default as contentConnexionPage } from "./connexion.json";
