export {
  RGA_MAP_STYLE_URL,
  DEFAULT_CENTER,
  ZOOM,
  MAX_BOUNDS,
  SOURCE_IDS,
  LAYER_IDS,
  RNB_SOURCE_LAYER,
  FLY_TO_DELAY,
  ALEA_COLORS,
  MARKER_ICON_URL,
  MARKER_ICON_SIZE,
} from "./rga-map.config";
