import { MATOMO_EVENTS, MatomoEvent } from "@/shared/constants/matomo.constants";
import { VulnerabiliteStep } from "./vulnerabilite-step.enum";

/**
 * Mapping étape vulnérabilité vers événement Matomo — même pattern que
 * `SIMULATEUR_STEP_EVENTS` du simulateur d'éligibilité.
 */
export const VULNERABILITE_STEP_EVENTS: Partial<Record<VulnerabiliteStep, MatomoEvent>> = {
  [VulnerabiliteStep.ADRESSE]: MATOMO_EVENTS.VULNERABILITE_STEP_ADRESSE,
  [VulnerabiliteStep.PENTE_TERRAIN]: MATOMO_EVENTS.VULNERABILITE_STEP_PENTE_TERRAIN,
  [VulnerabiliteStep.RESEAUX_ENTERRES]: MATOMO_EVENTS.VULNERABILITE_STEP_RESEAUX_ENTERRES,
  [VulnerabiliteStep.GRAVIER_PROPRETE]: MATOMO_EVENTS.VULNERABILITE_STEP_GRAVIER_PROPRETE,
  [VulnerabiliteStep.GOUTTIERES]: MATOMO_EVENTS.VULNERABILITE_STEP_GOUTTIERES,
  [VulnerabiliteStep.ARBRE_PROXIMITE]: MATOMO_EVENTS.VULNERABILITE_STEP_ARBRE_PROXIMITE,
  [VulnerabiliteStep.ARBRE_ESSENCE]: MATOMO_EVENTS.VULNERABILITE_STEP_ARBRE_ESSENCE,
  [VulnerabiliteStep.HAIES]: MATOMO_EVENTS.VULNERABILITE_STEP_HAIES,
  [VulnerabiliteStep.VEGETATION_PIED_FACADE]: MATOMO_EVENTS.VULNERABILITE_STEP_VEGETATION_PIED_FACADE,
  [VulnerabiliteStep.MITOYENNETE]: MATOMO_EVENTS.VULNERABILITE_STEP_MITOYENNETE,
  [VulnerabiliteStep.ENSOLEILLEMENT]: MATOMO_EVENTS.VULNERABILITE_STEP_ENSOLEILLEMENT,
};
